### ISSUE TITLE
persistant notification issue.

### ISSUE THREAD

**Issue by bharat127** [microg/IchnaeaNlpBackend#10]
In recent versions of this app, whenever it is enabled in mgUnifiedNlp app, there is a persistant notification that says to contribute to mozilla location services.

In previous versions of this app, there used to be an option whether or not to contribute to Mozilla Location Services with name defaulted to "mgUser". But now there is no such option and there is a persistant notification on status bar and lockscreen that says to contribute to mozLocService. 

Sure i can go to app info and uncheck "show notifications" for this app. But that is not a good solution. 

Please fix this..

IchnaeaBackend Version: 1.1.0
android version: 5.0.2
unified nlp version: 1.3.0

**Comment by mar-v-in** [comment]
You're right, somehow the code to disable the notification after the first start was lost. Will fix it the next version (temporary work-around: downgrade to old version, enable contribution, update to current version)

**Comment by breversa** [comment]
Bug confirmed with v1.1.0 on CyanogenMod 11.

Reverting back to v1.0.0, enabling contribution then upgrading to v1.1.0 did solve the issue. :-)

**Comment by NoSohoth** [comment]
I came here to report the issue, turns out you guys already have a work-around :)

It worked on CM12.1, thanks.

**Comment by a3nm** [comment]
I was also confused by this. Is there a plan to release a new version that would fix this? Thanks a lot!
