### ISSUE TITLE
Cell only version

### ISSUE THREAD

**Issue by carl091** [microg/IchnaeaNlpBackend#2]
First, I have to applaud the monumental efforts leading up to this point. Having a drop in replacement for Google location services is outstanding. Thank you.

Would it be possible to create a separate version or user configurable setting that only shares and requests information about cells and not wi-fi access points? Given the sensitivity of Wi-fi points I would prefer to use a different backend for those. I am aware of Local GSM Backend and it is useful, but downloading and creating the local database is resource and time intensive.

**Comment by mar-v-in** [comment]
This will definitely become an option in a future version.

**Comment by carl091** [comment]
Great! I'll keep an eye out.

**Comment by mar-v-in** [comment]
Feature added with 0.10.0 release.
