### ISSUE TITLE
Crashes when selected in UnifiedNlp settings

### ISSUE THREAD

**Issue by rugk** [microg/IchnaeaNlpBackend#21]
ROM: `CM-13.0-20160325-NIGHTLY-jfltexx`

Using the XposedUnifiedNlp module and [UnifiedNlp](https://f-droid.org/repository/browse/?fdid=org.microg.nlp) (v1.6.2-dirty) I can successfully access and configure the settings of the Mozilla Location services backend, but when I go (back) to the UnifiedNlp settings, activate this backend and click "ok" the default Android crash message is shown.

**Comment by mar-v-in** [comment]
Enable location permission in settings->apps or use v1.3.0 and disable/re-enable the backend.

**Comment by rugk** [comment]
Indeed this worked. Why is not this permission requested when starting the app/accessing as it should in Android 6?
Or why is not there at least a note in the settings that one should do this if it does not work? (Unexpected crashes are very bad UX :smile:)

**Comment by mar-v-in** [comment]
Support for Android 6 landed in UnifiedNlp v1.6.0 and Mozilla backend v1.3.0. If you use v1.3.0 it should ask for permission once activated and should not crash when it is not granted.

**Comment by rugk** [comment]
I am using the newest builds from FDroid. It seems for the mozilla backend v1.3 is not yet there.

**Comment by rugk** [comment]
BTW if all things I asked before are already solved, you may of course close this issue.
