### ISSUE TITLE
Build failed on F-Droid

### ISSUE THREAD

**Issue by Paviluf** [microg/IchnaeaNlpBackend#22]
Seems that there is an error on the version

```
Git checkout of 'vv1.3.1' failed

detail begin
error: pathspec 'vv1.3.1' did not match any file(s) known to git.

detail end
```

https://f-droid.org/wiki/page/org.microg.nlp.backend.ichnaea/lastbuild_20017

**Comment by mar-v-in** [comment]
Should be fixed by 35f6a7c

**Comment by Paviluf** [comment]
Thanks ! I will wait for the new build on F-Droid ;)

**Comment by Paviluf** [comment]
It's fixed, I could install v. 1.3.2 from F-Droid. Thank you !
