### ISSUE TITLE
Cannot enable on Android Nougat

### ISSUE THREAD

**Issue by ilpianista** [microg/IchnaeaNlpBackend#31]
I get a toast message with "Error initializing backend" when I try to enable this service.

logcat:
```
07-25 20:01:31.424  4579 23414 W ActivityManager: Permission Denial: Accessing service ComponentInfo{org.microg.nlp.backend.ichnaea/org.microg.nlp.backend.ichnaea.BackendService} from pid=30863, uid=10037 requires android.permission.ACCESS_COARSE_LOCATION
```

Looks like we need to [request permissions](https://developer.android.com/training/permissions/requesting.html)?

**Comment by mar-v-in** [comment]
Did you check that UnifiedNlp or GmsCore (whichever you use) has the correct permission as requested by the self-check?

**Comment by ilpianista** [comment]
Sorry for the late reply. You are right, solved.
