### ISSUE TITLE
Questions about widespread deployment

### ISSUE THREAD

**Issue by crankycoder** [microg/IchnaeaNlpBackend#32]
Hi!

I wasn't sure if there was a better place to ask general questions - but is there any data on how widely the microG library is being deployed?  We're seeing a lot of traffic on Ichnaea and microG is hitting it's API key rate-limit at Mozilla.  

![ck_location_server_timeboard___datadog](https://user-images.githubusercontent.com/4829/33038862-0158677e-ce04-11e7-9b42-77d351a3688c.jpg)
 
The traffic looks unusual - I think this is probably because of over aggressive querying of the service in the IchnaeaNlpBackend code which spins up a thread everytime `onCellChanged()` is invoked.

Is there an IRC channel or slack channel where I can ask someone questions?

thanks!

**Comment by mar-v-in** [comment]
I think this issue is mostly addressed with the v1.4.0 update. I'll leave it open for you to report in a week or so.

**Comment by crankycoder** [comment]
On our end - we just increased the API key limits for microG so that the user base isn't getting hit with HTTP 400 errors when the limit gets hit a couple hours before midnight UTC.

That should alleviate the immediate problem of users getting no location fix, but I'm hoping the new patch in the IchnaeaNlpBackend that just got landed will be a more permanent fix to reduce traffic load.

**Comment by crankycoder** [comment]
Where can I track the v1.4.0 release?  It's not entirely obvious on microg.org

**Comment by mar-v-in** [comment]
F-Droid seems to be unable to build the v1.4.0 update, so it's not deployed yet. You can track the status here: https://f-droid.org/wiki/page/org.microg.nlp.backend.ichnaea/lastbuild_20033
The underlying issue (not supporting gradle 4.8) was already fixed 2 weeks ago in their codebase, so all we can do now is wait for them to update their build servers.

**Comment by rugk** [comment]
So, any news here?

**Comment by crankycoder** [comment]
The build completed according to the fdroid link above.

A push out to users should have happened. If not - that's an fdroid issue.

**Comment by rugk** [comment]
So then this issue can be closed as it is fixed, is not it? :smile:
