### ISSUE TITLE
Mismatched versionCode

### ISSUE THREAD

**Issue by ale5000-git** [microg/IchnaeaNlpBackend#35]
I see [here](https://github.com/microg/IchnaeaNlpBackend/commit/6ad2926c42fbb0068e338e3aa2e29e640eea7321) 
> versionCode "20025"

but on [F-Droid](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.microg.nlp.backend.ichnaea.txt) there is 
> Build:1.3.3,20026

Is it 20025 or 20026 the correct one?

**Comment by mar-v-in** [comment]
This is an ugly hack anyway, it's only there for F-Droid servers to catch up version updates automatically.
