### ISSUE TITLE
Doesn't request background location permission in Android 10

### ISSUE THREAD

**Issue by eplinux** [microg/IchnaeaNlpBackend#52]
In Android 10, a new location permission was introduced. Therefore, apps have to request android.permission.ACCESS_BACKGROUND_LOCATION in order to access location when running in background. Manually allowing the backend to access background location via local terminal doesn't seem to work.

01-11 17:19:49.047  3493  7691 E WifiService: Permission violation - startScan not allowed for uid=10163, packageName=org.microg.nlp.backend.ichnaea, reason=java.lang.SecurityException: UID 10163 has no location permission

A workaround is proposed by adding this permission to the AndroidManifest.xml:

https://github.com/microg/android_packages_apps_GmsCore/issues/986

**Comment by breversa** [comment]
How did you install MinMicroG ? From Magisk or TWRP ?

I first installed it from Magisk and got the same error as you.

I then deinstalled the Magisk module, and installed MinMicroG via TWRP and voilà, problem solved ! :-)
