### ISSUE TITLE
Backend doesn't work with UMTS and LTE

### ISSUE THREAD

**Issue by Gitschubser** [microg/IchnaeaNlpBackend#6]
Hello,

I describe the problem. I use the backend with radio  GSM and here it works perfect, after them i test UMTS and LTE.
UMTS can only be locate via the Location Area Code and LTE via the Mobile Country Code.
The cellids exists all in the database and the GSM Location Backend works offline perfect.
I use a Moto G.

**Comment by mar-v-in** [comment]
Can you confirm that this is not caused by 
a) incompletely reported cell data from your phones modem (you can check this with SatStat)
b) missing data on the database server (check if their database that can be downloaded on the website contains the cells reported by SatStat)

**Comment by Gitschubser** [comment]
I can confirm that 
a, MCC, MNC, LAC (or TAC) and Cell ID are completely reported (check with SatStat, MozStumbler, Tower Collector, no -1 for the cellid or something)
b) the data exist in the file (https://location.services.mozilla.com/downloads) and the Local GSM Backend (https://github.com/n76/Local-GSM-Backend) works without problems with the generated database.
Can check the cellids quickly here at https://carto.rudloff.pro/gsm too.

**Comment by Gitschubser** [comment]
Here the request to ichnaea. Maybe @hannosch has a answer.
With LTE i get only a geoip result.

D/IchnaeaBackendService(15801): request: {"wifiAccessPoints":[],"cellTowers":[{"signalStrength":977,"psc":496,"cellId":12345678,"radioType":"lte","mobileCountryCode":262,"asu":95,"mobileNetworkCode":1,"locationAreaCode":12345}],"radioType":"gsm"}
D/IchnaeaBackendService(15801): response: {"location": {"lat": 51.0, "lng": 9.0}, "accuracy": 537000.0}
D/IchnaeaBackendService(15801): reporting: Location[ichnaea 51,000000,9,000000 acc=537000 t=?!? et=?!?]
V/NlpLocationBackendFuser( 1223): location=Location[network 51,000000,9,000000 acc=537000 et=+4h24m40s251ms {Bundle[{noGPSLocation=Location[network 51,000000,9,000000 acc=537000 et=+4h24m40s251ms {Bundle[{SERVICE_BACKEND_PROVIDER=ichnaea, SERVICE_BACKEND_COMPONENT=org.microg.nlp.backend.ichnaea/.BackendService}]}], SERVICE_BACKEND_PROVIDER=ichnaea, SERVICE_BACKEND_COMPONENT=org.microg.nlp.backend.ichnaea/.BackendService}]}]

**Comment by Gitschubser** [comment]
UMTS (Accuracy->Location Area Code):

D/IchnaeaBackendService(15801): request: {"wifiAccessPoints":[],"cellTowers":[{"signalStrength":-87,"psc":362,"cellId":1234567,"radioType":"umts","mobileCountryCode":262,"asu":91,"mobileNetworkCode":1,"locationAreaCode":12345}],"radioType":"gsm"}
D/IchnaeaBackendService(15801): Cells: 1
V/NlpLocationBackendFuser( 1223): location=Location[network 51,000000,9,000000 acc=537000 et=+4h24m47s157ms {Bundle[{noGPSLocation=Location[network 51,000000,9,000000 acc=537000 et=+4h24m47s157ms {Bundle[{SERVICE_BACKEND_PROVIDER=ichnaea, SERVICE_BACKEND_COMPONENT=org.microg.nlp.backend.ichnaea/.BackendService}]}], SERVICE_BACKEND_PROVIDER=ichnaea, SERVICE_BACKEND_COMPONENT=org.microg.nlp.backend.ichnaea/.BackendService}]}]
V/NlpLocationBackendFuser( 1223): location=Location[network 51,000000,9,000000 acc=537000 et=+4h24m47s157ms {Bundle[{noGPSLocation=Location[network 51,000000,9,000000 acc=537000 et=+4h24m47s157ms {Bundle[{SERVICE_BACKEND_PROVIDER=ichnaea, SERVICE_BACKEND_COMPONENT=org.microg.nlp.backend.ichnaea/.BackendService}]}]
D/IchnaeaBackendService(15801): response: {"location": {"lat": 48.xxxxxx, "lng": 11.xxxxxx}, "accuracy": 20000.0}

**Comment by Gitschubser** [comment]
Maybe there exist a close connection?

https://github.com/mozilla/ichnaea/issues/416

**Comment by hannosch** [comment]
This was a bug in ichnaea, the issue is fixed in the code and deployed to our staging server, should end up in production later this week.
