### ISSUE TITLE
missing PEERS_MAC_ADDRESS permission

### ISSUE THREAD

**Issue by Stricted** [microg/IchnaeaNlpBackend#62]
**Describe the bug**
when using the IchnaeaNlpBackend on android 11 it throws the following error
```
08-25 18:15:10.028  1066  2727 I WifiService: startScan uid=10133
08-25 18:15:10.030  1066  2727 E WifiService: Permission violation - startScan not allowed for uid=10133, packageName=org.microg.nlp.backend.ichnaea, reason=java.lang.SecurityException: UID 10133 has no location permission
08-25 18:15:10.032  2161  2161 D LocationFuser: Received no location from org.microg.nlp.backend.ichnaea/.BackendService
```

looking through the aosp code for android 11 it appears that it fails here http://aosp.opersys.com/xref/android-11.0.0_r47/xref/frameworks/opt/net/wifi/service/java/com/android/server/wifi/util/WifiPermissionsUtil.java#358

**To Reproduce**

**Expected behavior**

**Screenshots**

**System**
Android Version: [e.g. 10] 11
Custom ROM: [e.g. LineageOS 17.1] /e/

**Additional context**

**Comment by Stricted** [comment]
i may be wrong here, not sure exactly what is going on tbh

**Comment by mar-v-in** [comment]
The issue is that you haven't granted location permission to IchnaeaNlpBackend
